### ISSUE TITLE
Push tagged releases to Docker Registry

### ISSUE THREAD

**Issue by obviyus** [sergiotapia/torrentinim#14]
Greetings! I'd like to use Torrentinim in conjunction with `docker-compose` but I'd prefer to not build the image every time. If you're accepting PRs, I propose:
- Build the `Dockerfile` for every tagged release
- Publish the image to `ghcr.io/sergiotapia/torrentinim`

This could all be added to the existing `release-asset.yaml` workflow.

**Comment by sergiotapia** [comment]
Thanks, this sounds like a good idea. PRs welcome!
