### ISSUE TITLE
Create Docker Container version of Torrentinim

### ISSUE THREAD

**Issue by Draxter** [sergiotapia/torrentinim#2]
There currently is no Docker container version of Torrentinim on the docker hub. Creating one, would greatly expand the reach of Torrentinim among users.

**Comment by DelScipio** [comment]
To tell the truth, I don't see the need, at least for now. Is a single file, you run it works.

**Comment by sergiotapia** [comment]
I'll look into this this week. Thanks for the suggestion!

**Comment by sergiotapia** [comment]
Added a basic Dockerfile here: https://github.com/sergiotapia/torrentinim/blob/master/Dockerfile 

Still trying to figure out how to copy the sqlite file, I'm not familiar with Docker unfortunately.

**Comment by Draxter** [comment]
This is a good start. I had a go, and it builds and runs fine. Here are some ideas for future improvements:

- Add a VOLUME definition, so that users can store the database/crawl data in a directory that persists across container recreations
- Add a HEALTHCHECK definition, so that the health of the container is constantly monitored and restarted, if a failure occurs

Here's a good documentation on building dockerfiles, which should help: https://docs.docker.com/engine/reference/builder/

**Comment by driesvandamme** [comment]
@sergiotapia Could you add the repository to https://registry.hub.docker.com - That way people can find it from various sources! :-)

**Comment by usma0118** [comment]
I have experience with docker, just forked.
Will create PR soon.

**Comment by sergiotapia** [comment]
Thanks @usma0118 I am a real Docker noob and welcome a PR for sure. I appreciate your help.

**Comment by somedevreally** [comment]
any update?

**Comment by usma0118** [comment]
> any update?

I will be able to spend sometime in start of May.
