### ISSUE TITLE
How to use it on Linux?

### ISSUE THREAD

**Issue by slrslr** [sergiotapia/torrentinim#22]
Hello,
on Arch Linux, the package i have installed it like this: pamac build torrentinim-bin
$ man torrentinim
No manual entry for torrentinim
$ torrentinim -h
shows no help either, but launch the app which starts crawling some torrents without asking my permission
accidentaly i have found http://localhost:50123 in the output, but this site only notify me that the app is running, so i do not know how to manage the app - see no interface when i have lunched it via command line as shown above. And my Linux Arch based XFCE desktop environment menu does not find the torrentinim launch entry.

So maybe it can be improved to be less confusing to noob.

**Comment by sergiotapia** [comment]
There are a few ways to improve usability. For now I recommend checking the usage guide in the README. https://github.com/sergiotapia/torrentinim#usage-guide

**Comment by slrslr** [comment]
Please describe here, i do not understand the README description.
