### ISSUE TITLE
terminal displays all "Insert not successful" messages

### ISSUE THREAD

**Issue by johnhorner** [sergiotapia/torrentinim#29]
MacOS version v0.5.0 

The terminal shows nearly all "Insert not successful" messages, one for each item. No other error message or debugging info is displayed.

`torrentinim-data.db` file is 3.2MB, plenty of disk space left on the computer.

Let me know if I can provide any further information.

**Comment by sergiotapia** [comment]
Hey @johnhorner this is fixed in v0.7.0

You'll see exactly why a torrent is not being inserted, not more doubting what happened.

For example:

```
2022-09-18T21:54:25-04:00 [yts] Insert not successful: Two 4 One (2014) [WEBRip] [1080p] [YTS.MX] - UNIQUE constraint failed: torrents.canonical_url
```
