### ISSUE TITLE
App not crawling

### ISSUE THREAD

**Issue by telot** [sergiotapia/torrentinim#3]
Ran ./torrentinim nuke_my_database as first time run on ubuntu 18.04 server.  

./torrentinim nuke_my_database
[database] Initializing database
[eztv] Starting EZTV crawl
[1337x] Starting 1337x crawl
[1337x] Download html: https://1337x.to/cat/Anime/1/
[nyaa] Starting Nyaa crawl
[nyaa-pantsu] Starting NyaaPantsu crawl
[nyaa-sukebei] Starting Nyaa Sukebei crawl
[yts] Starting YTS crawl
[torrentdownloads] Starting TorrentDownloads.me crawl
[thepiratebay] Starting ThePirateBay crawl
[rarbg] Starting Rarbg crawl
INFO Jester is making jokes at http://0.0.0.0:50123
Starting 24 threads
Listening on port 50123

And it stops there.  I let it run for 1 hour with no other output from the app.  Checking the database, its size is 1.1MB.  I ran it on another ubuntu 18.04 server box with the same results.  
[torrentinim-data.db.zip](https://github.com/sergiotapia/torrentinim/files/5396103/torrentinim-data.db.zip)

**Comment by sergiotapia** [comment]
It seems this bug has some back. It has something to do with Nim's async stdlib. Before I fixed it by setting the .cfg config for macosx but it seems to have spread to Linux. I'll reach out to smarter people in the forums and hopefully they can help.

**Comment by sergiotapia** [comment]
This is now fixed in v.0.2.1 @telot 

https://github.com/sergiotapia/torrentinim/releases/tag/v0.2.1

Let me know!
