### ISSUE TITLE
Search either not picking items up or picking random items

### ISSUE THREAD

**Issue by ialexpw** [sergiotapia/torrentinim#8]
Had a quick look at this and setup a version to trial, but having issues with the search as it seems to either pick up random results, or none at all.

e.g. In my database I have a few like;

![image](https://user-images.githubusercontent.com/7994724/115879394-8409db00-a441-11eb-9af6-14308b5beb8d.png)

When searching from the web I get random results returned (/search?query=surfing&page=1);

![image](https://user-images.githubusercontent.com/7994724/115879491-9f74e600-a441-11eb-8fb6-3ddad85d3ec6.png)

Possibly something I am missing? Although this seems to do it for most results I try and return. Any ideas what I could try?

**Comment by sergiotapia** [comment]
I can't seem to reproduce this - it may have been fixed in the interim. Search is working fine, even with japanese and chinese query terms. 

Please let me know if this happens to you again and we can figure it out. Thanks!
