### ISSUE TITLE
Porter tokenizer yields no search results when querying non-ASCII characters.

### ISSUE THREAD

**Issue by motord** [sergiotapia/torrentinim#9]
Should unicode61 tokenizer be used?

**Comment by sergiotapia** [comment]
Could you share the title you're trying to search again and what search term you're using?

**Comment by sergiotapia** [comment]
I just tried search against chinese and japanese characters and it returns results accurately. This may have been fixed in the interim. Please let me know if this happens to you again. Thank you!
